module.exports = [
  {
    id: 1,
    name: "Card 1",
    description: "This is card number 1.",
    user_id: 1,
  },
  {
    id: 2,
    name: "Card 2",
    description: "This is card number 2.",
    user_id: 1,
  },
  {
    id: 3,
    name: "Card 3",
    description: "This is card number 3.",
    user_id: 1,
  },
  {
    id: 4,
    name: "Card 4",
    description: "This is card number 4.",
    user_id: 1,
  },
  {
    id: 5,
    name: "Card 5",
    description: "This is card number 5.",
    user_id: 1,
  },
  {
    id: 6,
    name: "Card 6",
    description: "This is card number 6.",
    user_id: 1,
  },
  {
    id: 7,
    name: "Card 7",
    description: "This is card number 7.",
    user_id: 1,
  },
  {
    id: 8,
    name: "Card 8",
    description: "This is card number 8.",
    user_id: 1,
  },
  {
    id: 9,
    name: "Card 9",
    description: "This is card number 9.",
    user_id: 1,
  },
  {
    id: 10,
    name: "Card 10",
    description: "This is card number 10.",
    user_id: 1,
  },
  {
    id: 11,
    name: "Card 11",
    description: "This is card number 11.",
    user_id: 1,
  },
  {
    id: 12,
    name: "Card 12",
    description: "This is card number 12.",
    user_id: 1,
  },
  {
    id: 13,
    name: "Card 13",
    description: "This is card number 13.",
    user_id: 1,
  },
];
