module.exports = [
  {
    id: 1,
    name: "Rule 1",
    description: "This is rule number 1.",
    user_id: 1,
  },
  {
    id: 2,
    name: "Rule 2",
    description: "This is rule number 2.",
    user_id: 1,
  },
  {
    id: 3,
    name: "Rule 3",
    description: "This is rule number 3.",
    user_id: 1,
  },
  {
    id: 4,
    name: "Rule 4",
    description: "This is rule number 4.",
    user_id: 1,
  },
  {
    id: 5,
    name: "Rule 5",
    description: "This is rule number 5.",
    user_id: 1,
  },
  {
    id: 6,
    name: "Rule 6",
    description: "This is rule number 6.",
    user_id: 1,
  },
  {
    id: 7,
    name: "Rule 7",
    description: "This is rule number 7.",
    user_id: 1,
  },
  {
    id: 8,
    name: "Rule 8",
    description: "This is rule number 8.",
    user_id: 1,
  },
  {
    id: 9,
    name: "Rule 9",
    description: "This is rule number 9.",
    user_id: 1,
  },
  {
    id: 10,
    name: "Rule 10",
    description: "This is rule number 10.",
    user_id: 1,
  },
  {
    id: 11,
    name: "Rule 11",
    description: "This is rule number 11.",
    user_id: 1,
  },
  {
    id: 12,
    name: "Rule 12",
    description: "This is rule number 12.",
    user_id: 1,
  },
  {
    id: 13,
    name: "Rule 13",
    description: "This is rule number 13.",
    user_id: 1,
  },
];
